# Generated by Django 4.2 on 2023-04-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lastn_ame',
            new_name='last_name',
        ),
    ]
